### PR TITLE
Test with Ruby 2.6, 2.7

### PR DESCRIPTION
**Pull request by aried3r**

### CODE REVIEW

**Comment by aried3r** [comment]
Hmm, seems like Travis is not active for this repo?
https://travis-ci.org/github/shrinerb/content_disposition

**Comment by benkoshy** [comment]
@hmistry 

Was going to make this PR myself when I saw Anton beat me to it.

I'm happy to set up travis set up with this gem if you're happy to add me as collab? 

image

Or alternatively I think it can be enabled by an admin via this link here which Anton provided: https://travis-ci.org/github/shrinerb/content_disposition

chrs
Ben

**Comment by jrochkind** [comment]
Hey travis is also ending their support for open source for free. (Travis is also being really obscure when talking about it, so it's not immediately obvious from their announcements if you just skim them, but really that's what's going on). 

* https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Might make more sense to move over to Github Actions?

i moved a bunch of repos from travis to Github Actions in the past couple weeks, I can find some time to look into it here, unless someone else wants to do it?  I am not sure if the test suite has anything that will be especially hard to set up on Github Actions, if it doesn't have any unusual dependencies it should be straightforward.

**Comment by janko** [comment]
@jrochkind I would love to switch all the Shrine-related projects to GitHub Actions, I'm still getting ready to read your excellent dive into this. But I'd be happy if someone sends PRs before that 😉

**Comment by jrochkind** [comment]
OK cool. It looks like the .travis.yml has some custom setup, for instance for minio -- do you think the .travis.yml is reasonably up to date, like it would have been enough for succesful tests, even though travis isn't currently running?

I'll see if I can get Github Actions working based on the .travis.yml, for this repo, I think I can find some time to do it today or tomorrow. 

the main thing Github Actions lacks compared to travis is any good built-in way to do "allowed_failures". To begin with I'll probably leave ruby-head and jruby-head out entirely?

**Comment by jrochkind** [comment]
Done! Here at #6, and in main shrine repo at https://github.com/shrinerb/shrine/pull/510

**Comment by aried3r** [comment]
Closing in favor of #6.

**Pull request closed without merging**
